 @startuml

!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v16.0/dist
!define VMWARE_SPRITEURL https://raw.githubusercontent.com/chrisccoy/plantuml-sprites/main
!include AWSPuml/AWSCommon.puml
!include AWSPuml/Groups/AWSCloud.puml
!include AWSPuml/Containers/EKSCloud.puml
!include AWSPuml/General/all.puml
!include AWSPuml/DeveloperTools/CodeArtifact.puml
!include AWSPuml/Database/Database.puml
!include VMWARE_SPRITEURL/vmware.puml
!include VMWARE_SPRITEURL/griffin.puml

actor User
participant "<color:$AWS_COLOR_SMILE><$Client></color>\nFrontend\nApplication" as Frontend
participant "<color:$AWS_COLOR_SMILE><$Servers></color>\nBackend\n(BFF)" as BFF
participant "<color:$AWS_COLOR_SMILE><$GitRepository></color>\nGitLab" as gitlab
participant "<color:$AWS_COLOR_SMILE><$vmware></color>\npCloud" as pcloud
participant "<color:$AWS_COLOR_SMILE><$axway_logo_icon></color>\nfoo" as foo
participant "<color:$AWS_COLOR_SMILE><$Database></color>\nDatabase" as DB



User -> Frontend: Provide service details for creation
Frontend -> BFF: Initiate service creation flow

BFF -> gitlab: Validate Data
gitlab --> BFF: Confirm Data
BFF -> gitlab: Create New Blank Repo
gitlab --> BFF: Repo Creation Result
BFF -> pcloud: Provision or Resuse VM for CI/CD Runner
pcloud --> BFF: Runner Result

BFF -> gitlab: Upload Scaffolded\nProject Template
gitlab --> BFF: Scaffolded Project Result
note right
As the scaffolded project is loaded
appropriate template substitutions are made, based on provided inputs. 
Including information related to container creation, CI/CD, Helm, etc
end note
BFF -> gitlab: Create New Blank Repo
gitlab --> BFF: Repo Creation Result

BFF -> DB: Add Service to Catalog
DB -> BFF: Catalog Reslt

@enduml